---
name: FTs
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
    branches:
      # Branches from forks have the form 'user:branch-name' so we only run
      # this job on pull_request events for branches that look like fork
      # branches. Without this we would end up running this job twice for non
      # forked PRs, once for the push and then once for opening the PR.
      # See https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/10
      - "**:**"
jobs:
  functional-tests:
    name: FTs
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.6

      - name: Install Gauge
        uses: getgauge/setup-gauge@master
        with:
          gauge-version: master
          gauge-plugins: python, html-report, screenshot

      - name: FTs
        run: gauge run specs

      - name: Upload logs
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ft-logs
          path: logs

      - name: Upload Gauge specs html report
        uses: actions/upload-artifact@v2
        with:
          name: gauge-html-report
          path: reports/html-report/
